"""Dependency-free build. Source modules remain the authoritative editable files."""
from pathlib import Path
import re
import hashlib
root=Path(__file__).parent
parts=[]
for name in ['core.mjs','renderer.mjs','audio.mjs','game.mjs']:
    source=(root/name).read_text()
    source=re.sub(r'^import .*?;\n','',source,flags=re.M)
    source=re.sub(r'\bexport (?=(?:class|const|function)\b)','',source)
    parts.append(source)
bundle='/* ECHO HUNT 1.0 — generated by build.py; no external dependencies */\n(()=>{\n'+ '\n'.join(parts)+'\n})();\n'
fingerprint=lambda text:hashlib.sha256(text.encode()).hexdigest()[:12]
version=fingerprint(bundle)
bundle='window.echoBuild="'+version+'";\n'+bundle
(root/'bundle.js').write_text(bundle)
html=(root/'index.template.html').read_text()
css=(root/'style.css').read_text()
published=html.replace('href="style.css"','href="style.css?v='+fingerprint(css)+'"').replace('src="bundle.js"','src="bundle.js?v='+version+'"')
(root/'index.html').write_text(published)
html=html.replace('<link rel="stylesheet" href="style.css">','<style>'+css+'</style>')
html=re.sub(r'<script src="bundle.js"[^>]*></script>',lambda m:'<script>'+bundle.replace('</script','<\\/script')+'</script>',html)
(root/'echo-hunt.html').write_text(html)
qa=(root/'qa.template.html').read_text().replace('src="index.html?qa=1&touch=1"','src="index.html?qa=1&touch=1&v='+version+'"').replace('src="tests/browser.qa.js"','src="tests/browser.qa.js?v='+fingerprint((root/'tests/browser.qa.js').read_text())+'"')
(root/'qa.html').write_text(qa)
print('Built static files and self-contained echo-hunt.html / '+version)
