"""Dependency-free build. Source modules remain the authoritative editable files."""
from pathlib import Path
import re
root=Path(__file__).parent
parts=[]
for name in ['core.mjs','renderer.mjs','audio.mjs','game.mjs']:
    source=(root/name).read_text()
    source=re.sub(r'^import .*?;\n','',source,flags=re.M)
    source=re.sub(r'\bexport (?=(?:class|const|function)\b)','',source)
    parts.append(source)
bundle='/* ECHO HUNT 1.0 — generated by build.py; no external dependencies */\n(()=>{\n'+ '\n'.join(parts)+'\n})();\n'
(root/'bundle.js').write_text(bundle)
html=(root/'index.html').read_text()
html=html.replace('<link rel="stylesheet" href="style.css">','<style>'+(root/'style.css').read_text()+'</style>')
html=re.sub(r'<script src="bundle.js"[^>]*></script>',lambda m:'<script>'+bundle.replace('</script','<\\/script')+'</script>',html)
(root/'echo-hunt.html').write_text(html)
print('Built bundle.js and self-contained echo-hunt.html')
