import {Game,DEFAULTS,WEAPONS,BALANCE,clamp,angle,direction,lineClear} from './core.mjs';
import {Renderer} from './renderer.mjs';
import {AudioEngine} from './audio.mjs';
const $=id=>document.getElementById(id),touch=matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0||new URLSearchParams(location.search).has('touch');
if(touch)document.body.classList.add('touch');
let cfg={...DEFAULTS};try{cfg={...cfg,...JSON.parse(localStorage.getItem('echo-hunt-settings')||'{}')};}catch{}
for(const [k,list]of Object.entries({role:['human','hidden','random'],difficulty:['easy','normal','hard'],quality:['low','medium','high']}))if(!list.includes(cfg[k]))cfg[k]=DEFAULTS[k];
for(const [k,min,max]of [['target',3,100],['duration',120,900],['respawn',2,8],['sensitivity',.3,2.5],['volume',0,1],['weapon',0,2]])cfg[k]=Number.isFinite(+cfg[k])?clamp(+cfg[k],min,max):DEFAULTS[k];
for(const [k,values]of Object.entries({duration:[120,300,600,900],respawn:[2,4,8]}))if(!values.includes(+cfg[k]))cfg[k]=DEFAULTS[k];
let game=new Game(cfg),renderer,mode='title',night=false,previousPanel=null,recoil=0,accumulator=0,last=0,toastUntil=0,hitUntil=0,hurtUntil=0,feed=[],lastHud=0,frameCount=0,fpsAt=0,fps=0,lastRole='',lockWasActive=false;
const audio=new AudioEngine(),keys=new Set(),input={joyX:0,joyY:0,attack:false,jump:false},pointers=new Map();let joyId=null,lookId=null,lookX=0,lookY=0;
function save(){try{localStorage.setItem('echo-hunt-settings',JSON.stringify(cfg));}catch{}audio.setVolume(cfg.volume);if(renderer)renderer.cfg=cfg;}
function resetInput(){$('scoreboard').hidden=true;keys.clear();pointers.clear();input.joyX=input.joyY=0;input.attack=input.jump=false;joyId=lookId=null;$('stick').style.transform='translate(0,0)';}
function toast(text,seconds=2.5){$('toast').textContent=text;toastUntil=performance.now()/1000+seconds;}
function table(){const a=[...game.actors].sort((a,b)=>b.score-a.score);return '<table class="score-table"><thead><tr><th>RANK</th><th>UNIT</th><th>PT</th><th>K / D</th></tr></thead><tbody>'+a.map((v,i)=>'<tr class="'+(v.id===0?'me':'')+'"><td>'+ (a.findIndex(b=>b.score===v.score)+1)+'</td><td>'+v.name+'</td><td>'+v.score+'</td><td>'+v.kills+' / '+v.deaths+'</td></tr>').join('')+'</tbody></table>';}
function lock(){if(touch||!$('world').requestPointerLock)return;try{const promise=$('world').requestPointerLock();if(promise?.catch)promise.catch(()=>toast('右ドラッグでも視点を操作できます',3));}catch{}}
function exitLock(){if(document.pointerLockElement)document.exitPointerLock?.();}
function showPanel(id){$('modalLayer').hidden=false;for(const el of document.querySelectorAll('#modalLayer>.panel'))el.hidden=el.id!==id;}
function closePanel(){if(mode==='paused'){showPanel('pausePanel');return;}$('modalLayer').hidden=true;previousPanel=null;}
function pause(reason='呼吸を整えて、再び区画へ。'){if(mode!=='playing')return;mode='paused';resetInput();exitLock();$('pauseReason').textContent=reason;showPanel('pausePanel');}
function resume(){audio.unlock();mode='playing';$('modalLayer').hidden=true;resetInput();last=performance.now();accumulator=0;lock();}
function start(){try{readSettings();const unlocked=audio.unlock();game.cfg={...cfg};game.reset();night=false;recoil=0;feed=[];lastRole='';mode='playing';resetInput();$('titleScreen').hidden=true;$('hud').hidden=false;$('controls').hidden=false;$('modalLayer').hidden=true;document.body.classList.add('playing');last=performance.now();accumulator=0;toast(game.actors[0].role==='hidden'?'ヒドゥンになりました\n近づいて攻撃。撃破で透明度回復。':game.actors[0].role==='traitor'?'裏切り者です\n人間を狙って得点。ヒドゥンは攻撃不可。':'索敵開始\nゆがむ輪郭と足音を探してください',4);lock();unlocked.then(ok=>{if(!ok&&mode==='playing')toast('音声を開始できませんでした。再開操作で再試行します',3);});}catch(e){window.showFatal(e.stack||String(e));}}
function home(){mode='title';resetInput();exitLock();$('titleScreen').hidden=false;$('hud').hidden=true;$('controls').hidden=true;$('modalLayer').hidden=true;$('scoreboard').hidden=true;document.body.classList.remove('playing');game.cfg={...cfg};game.reset();night=false;}
function end(){mode='ended';resetInput();exitLock();const player=game.actors[0],rank=1+game.actors.filter(a=>a.score>player.score).length;$('resultTitle').textContent=rank===1?'区画を制圧':'作戦終了';$('resultSummary').textContent='あなたは '+rank+' 位 / '+player.score+' 点 / '+player.kills+' 撃破 / '+player.deaths+' ダウン';$('resultScores').innerHTML=table();showPanel('resultPanel');}
function loadSettings(){for(const k of ['quality','difficulty','sensitivity','volume','target','duration','respawn'])$(k).value=cfg[k];for(const k of ['flashlight','supplies','traitor'])$(k).checked=cfg[k];$('sensValue').value=Number(cfg.sensitivity).toFixed(1);$('volumeValue').value=Math.round(cfg.volume*100)+'%';for(const b of document.querySelectorAll('[data-role]'))b.classList.toggle('selected',b.dataset.role===cfg.role);for(const b of document.querySelectorAll('[data-weapon]'))b.classList.toggle('selected',+b.dataset.weapon===+cfg.weapon);}
function readSettings(){for(const k of ['quality','difficulty'])cfg[k]=$(k).value;for(const k of ['sensitivity','volume','target','duration','respawn'])cfg[k]=Number($(k).value);cfg.target=clamp(Math.round(cfg.target)||15,3,100);for(const k of ['flashlight','supplies','traitor'])cfg[k]=$(k).checked;save();loadSettings();}
loadSettings();audio.setVolume(cfg.volume);
for(const k of ['quality','difficulty','sensitivity','volume','target','duration','respawn','flashlight','supplies','traitor'])$(k).addEventListener(['sensitivity','volume'].includes(k)?'input':'change',()=>{readSettings();});
for(const b of document.querySelectorAll('[data-role]'))b.addEventListener('click',()=>{cfg.role=b.dataset.role;save();loadSettings();});
for(const b of document.querySelectorAll('[data-weapon]'))b.addEventListener('click',()=>{cfg.weapon=+b.dataset.weapon;save();loadSettings();});
$('start').addEventListener('click',start);$('replay').addEventListener('click',start);$('resume').addEventListener('click',resume);$('quit').addEventListener('click',home);$('resultHome').addEventListener('click',home);$('pauseBtn').addEventListener('click',()=>pause());
$('settingsOpen').addEventListener('click',()=>showPanel('settingsPanel'));$('helpOpen').addEventListener('click',()=>showPanel('helpPanel'));$('pauseSettings').addEventListener('click',()=>showPanel('settingsPanel'));$('pauseHelp').addEventListener('click',()=>showPanel('helpPanel'));for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',()=>{readSettings();closePanel();});
function vision(){if(mode!=='playing'||!game.actors[0].alive)return;if(game.actors[0].role==='hidden'){night=!night;toast('ナイトビジョン '+(night?'ON':'OFF'),1);}else toast('暗視はヒドゥン専用です',1.2);}
function flash(){if(mode!=='playing'||!game.actors[0].alive)return;const p=game.actors[0];if(game.cfg.flashlight&&p.role!=='hidden'){p.flashlight=!p.flashlight;toast('懐中電灯 '+(p.flashlight?'ON':'OFF'),1);}else toast('設定の追加ルールで懐中電灯を有効にできます',2);}
function action(name){if(mode!=='playing')return;const p=game.actors[0];if(name==='reload')game.reload(p);if(name==='weapon')game.changeWeapon(p,p.weapon+1);if(name==='vision')vision();if(name==='flash')flash();}
for(const [id,name]of [['attackBtn','attack'],['jumpBtn','jump'],['reloadBtn','reload'],['weaponBtn','weapon'],['visionBtn','vision'],['flashBtn','flash']]){
 $(id).addEventListener('pointerdown',e=>{if(mode!=='playing')return;e.preventDefault();e.stopPropagation();try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}pointers.set(e.pointerId,name);if(name==='attack')input.attack=true;else if(name==='jump')input.jump=true;else action(name);});
}
function release(e){const name=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(name==='attack')input.attack=[...pointers.values()].includes('attack');if(name==='jump')input.jump=false;if(e.pointerId===joyId){joyId=null;input.joyX=input.joyY=0;$('stick').style.transform='translate(0,0)';}if(e.pointerId===lookId)lookId=null;if(e.pointerType==='mouse'&&e.button===0)input.attack=false;}
for(const ev of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(ev,release);
function joystick(e){const r=$('joystick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.max(1,Math.hypot(dx,dy)/(r.width*.34));input.joyX=clamp(dx/(r.width*.34*d),-1,1);input.joyY=clamp(-dy/(r.height*.34*d),-1,1);$('stick').style.transform='translate('+dx/d+'px,'+dy/d+'px)';}
$('joystick').addEventListener('pointerdown',e=>{if(joyId!==null||mode!=='playing')return;e.preventDefault();joyId=e.pointerId;try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}joystick(e);});$('joystick').addEventListener('pointermove',e=>{if(e.pointerId===joyId){e.preventDefault();joystick(e);}});
function look(dx,dy){const p=game.actors[0];if(!p.alive||mode!=='playing')return;const sensitivity=cfg.sensitivity*(touch?.0045:.0025);p.yaw+=clamp(dx,-150,150)*sensitivity;p.pitch=clamp(p.pitch-dy*sensitivity,-1.35,1.35);}
$('lookZone').addEventListener('pointerdown',e=>{if(mode!=='playing')return;e.preventDefault();if(e.pointerType==='mouse'){if(e.button===0){input.attack=true;pointers.set(e.pointerId,'attack');}if(!document.pointerLockElement&&e.button===2){lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}}}else if(lookId===null){lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;try{e.currentTarget.setPointerCapture(e.pointerId);}catch{}}});
$('lookZone').addEventListener('pointermove',e=>{if(e.pointerId===lookId&&!document.pointerLockElement){look(e.clientX-lookX,e.clientY-lookY);lookX=e.clientX;lookY=e.clientY;}});
document.addEventListener('mousemove',e=>{if(document.pointerLockElement)look(e.movementX,e.movementY);});document.addEventListener('mousedown',e=>{if(document.pointerLockElement&&e.button===0&&mode==='playing')input.attack=true;});document.addEventListener('mouseup',e=>{if(e.button===0)input.attack=false;});document.addEventListener('contextmenu',e=>{if(mode==='playing')e.preventDefault();});document.addEventListener('pointerlockchange',()=>{const locked=!!document.pointerLockElement;if(lockWasActive&&!locked)pause('マウス固定を解除しました。再開でゲームに戻ります。');lockWasActive=locked;});
document.addEventListener('keydown',e=>{if(e.code==='Escape'){if(mode==='playing')pause();return;}if(mode!=='playing'||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(['Space','Tab','KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;switch(e.code){case 'KeyR':action('reload');break;case 'KeyQ':action('weapon');break;case 'KeyN':vision();break;case 'KeyF':flash();break;case 'Space':input.jump=true;break;case 'Digit1':case 'Digit2':case 'Digit3':game.changeWeapon(game.actors[0],Number(e.code.slice(-1))-1);break;case 'Tab':$('scoreboard').innerHTML=table();$('scoreboard').hidden=false;break;}});
document.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')input.jump=false;if(e.code==='Tab')$('scoreboard').hidden=true;});
document.addEventListener('visibilitychange',()=>{resetInput();if(document.hidden){pause('タブを離れたため一時停止しました。');audio.ctx?.suspend().catch(()=>{});}last=performance.now();accumulator=0;});window.addEventListener('blur',()=>{resetInput();pause('操作の切り替えを検知し、一時停止しました。');});window.addEventListener('pagehide',()=>{resetInput();pause();});window.addEventListener('pageshow',()=>{resetInput();last=performance.now();accumulator=0;});window.addEventListener('resize',()=>{resetInput();renderer?.resize();orientation();});window.addEventListener('orientationchange',()=>{resetInput();pause('画面の向きを変更しました。再開してください。');orientation();});
function orientation(){$('rotateHint').hidden=!(touch&&innerHeight>innerWidth&&mode==='playing');}
// Prevent browser gestures only over the actual game controls.
for(const id of ['controls','world'])for(const name of ['touchstart','touchmove','gesturestart','gesturechange','dblclick'])$(id).addEventListener(name,e=>{if(mode==='playing')e.preventDefault();},{passive:false});
$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();pause();window.showFatal('3D描画が中断されました。ほかのタブを閉じ、再読み込みしてください。画質「軽量」もお試しください。');});
function events(){const p=game.actors[0];for(const e of game.events.splice(0)){
 if(e.type==='sound')audio.play(e.kind,{x:e.x,y:e.y,z:e.z},p,game.map,game.actors[e.id].weapon);
 if(e.type==='attack'&&e.id===0){recoil=Math.min(.08,recoil+(e.melee?.018:WEAPONS[p.weapon].recoil));if(!e.melee)p.pitch=clamp(p.pitch+WEAPONS[p.weapon].recoil*.25,-1.35,1.35);}
 if(e.type==='hit'){if(e.from===0){hitUntil=performance.now()/1000+.13;audio.play('hit',null,p,game.map);}if(e.id===0){hurtUntil=performance.now()/1000+.7;const a=game.actors[e.from];if(a){let yaw=Math.atan2(a.x-p.x,-(a.z-p.z));$('damageDirection').style.transform='rotate('+angle(yaw-p.yaw)+'rad)';}}}
 if(e.type==='kill'){const k=e.from===null?'環境':game.actors[e.from].name,v=game.actors[e.id].name;feed.unshift({text:k+'  ▸  '+v+(e.pts?'  +'+e.pts:''),you:e.from===0||e.id===0,until:performance.now()/1000+5});feed=feed.slice(0,4);if(e.from===0)toast('撃破 +'+e.pts+' PT',1.5);}
 if(e.type==='role'&&e.id===0){night=false;resetInput();audio.play('role',null,p,game.map);if(game.time>1)toast(e.role==='hidden'?'ヒドゥンに交代\n安全な地点に転送されました':e.role==='traitor'?'裏切り者に選ばれました':'人間として再配置',3);}
 if(e.type==='respawn'&&e.id===0){night=false;resetInput();toast('人間として復活 / 一時的に保護中',2);}
 if(e.type==='supply'&&e.id===0){toast('補給獲得 / '+e.name,2);audio.play('supply',null,p,game.map);}
 if(e.type==='reload'&&e.id===0)audio.play('reload',null,p,game.map);
 if(e.type==='end')end();
}}
function hud(now){const p=game.actors[0],hidden=p.role==='hidden';if(p.role!==lastRole){lastRole=p.role;$('roleBadge').textContent=hidden?'HIDDEN':p.role==='traitor'?'TRAITOR':'HUMAN';$('objective').textContent=hidden?'背後へ回り、人間を倒せ':p.role==='traitor'?'人間を狙って得点':'透明なヒドゥンを探せ';$('roleBadge').style.color=hidden?'#81e7e9':p.role==='traitor'?'#ffaf77':'';$('reloadBtn').hidden=hidden;$('weaponBtn').hidden=hidden;$('visionBtn').hidden=!hidden;$('flashBtn').hidden=hidden||!game.cfg.flashlight;}
 if(!hidden)night=false;
 $('hp').textContent=Math.max(0,Math.ceil(p.hp));$('hpBar').style.width=clamp(p.hp/p.maxHP*100,0,100)+'%';$('hpBar').style.background=p.hp<35?'#fa8160':'#d1f477';$('cloakPanel').hidden=!hidden;$('cloakBar').style.width=p.cloak*100+'%';
 const left=Math.max(0,Math.ceil(game.cfg.duration-game.time));$('timer').textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0');$('goalLabel').textContent=game.cfg.target+' PT MATCH';$('score').textContent=p.score;$('topScore').textContent=Math.max(...game.actors.map(a=>a.score));$('weaponName').textContent=hidden?'PHASE BLADES':WEAPONS[p.weapon].name;$('ammo').textContent=hidden?'近接':p.ammo[p.weapon];$('reserve').textContent=hidden?'2.3 m':'/ '+p.reserve[p.weapon];$('reloadState').textContent=p.reload?'リロード '+p.reload.toFixed(1)+'s':p.shield>0?'復活保護 '+p.shield.toFixed(1)+'s':hidden&&p.reveal>0?'姿が露出しています':'';
 $('toast').style.opacity=now<toastUntil?'1':'0';$('hitmarker').style.opacity=now<hitUntil?'1':'0';$('vignette').style.opacity=now<hurtUntil?'1':'0';$('damageDirection').style.opacity=now<hurtUntil?'1':'0';feed=feed.filter(e=>e.until>now);$('killfeed').innerHTML=feed.map(e=>'<div class="'+(e.you?'feed-you':'')+'">'+e.text+'</div>').join('');
 $('respawnNotice').hidden=p.alive;if(!p.alive)$('respawnNotice').textContent='ダウン\n'+Math.max(0,Math.ceil(p.respawnAt-game.time))+'秒後に人間として復活';$('buffs').textContent=Object.entries(p.buffs).filter(([k,v])=>v>game.time).map(([k,v])=>({scan:'探知',speed:'加速',damage:'攻撃強化'}[k])+' '+Math.ceil(v-game.time)+'s').join(' / ');$('visionBtn').style.borderColor=night?'#d1f477':'';$('flashBtn').style.borderColor=p.flashlight?'#d1f477':'';
 const degrees=((p.yaw*180/Math.PI)%360+360)%360;$('compass').textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(degrees/45)%8]+'  '+String(Math.round(degrees)).padStart(3,'0');$('fps').textContent=fps+' FPS';orientation();}
let failed=false;
function frame(time){if(failed)return;requestAnimationFrame(frame);try{const elapsed=Math.min((time-(last||time))/1000,.1);last=time;if(mode==='playing'){
 accumulator+=elapsed;let ticks=0;while(accumulator>=1/60&&ticks++<5){const p=game.actors[0],front=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)+input.joyY,side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+input.joyX;game.update(1/60,{x:Math.sin(p.yaw)*front+Math.cos(p.yaw)*side,z:-Math.cos(p.yaw)*front+Math.sin(p.yaw)*side,attack:input.attack,jump:input.jump});input.jump=false;events();accumulator-=1/60;if(mode!=='playing'){accumulator=0;break;}}
 }recoil*=Math.exp(-elapsed*15);renderer.render(game,null,night,mode==='title',recoil);frameCount++;if(time-fpsAt>1000){fps=Math.round(frameCount*1000/(time-fpsAt));fpsAt=time;frameCount=0;}if(time-lastHud>70){hud(time/1000);lastHud=time;}
 }catch(e){failed=true;window.showFatal(e.stack||String(e));}}
try{renderer=new Renderer($('world'),game.map,cfg);window.gameReady=true;clearTimeout(window.loadTimer);$('loadStatus').textContent='READY / オフライン演習・8名 / 外部通信なし'+(renderer.kind==='canvas3d'?' / 軽量3Dモード':'');requestAnimationFrame(frame);}catch(e){window.showFatal(e.stack||String(e));}
// Read-only diagnostics are available without changing a live match.
window.echoDiagnostics=()=>({build:window.echoBuild,ready:!!window.gameReady,mode,night,frames:renderer?.frames,actors:game.actors.length,hiddenCount:game.actors.filter(a=>a.alive&&a.role==='hidden').length,metrics:{...game.metrics},webgl:!!renderer?.gl,renderer:renderer?.kind,renderSize:[renderer?.width,renderer?.height],audio:audio.ctx?.state||'not-started',input:{...input},navNodes:game.nav.nodes.length});
// Explicit QA mode for repeatable integration checks; absent during ordinary play.
if(new URLSearchParams(location.search).has('qa'))window.echoQA={get game(){return game;},get renderer(){return renderer;},get mode(){return mode;},start,pause,resume,home,resetInput,events,hud,look,vision,flash,input,keys,get audio(){return audio;}};
